version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app  # Maps local files to the container for live updates
      - /usr/src/app/node_modules  # Prevents overwriting node_modules in container
    ports:
      - "3000:3000"
    command: npm run dev  # Use nodemon to watch for changes and restart
